### ISSUE TITLE
Non standard markup tags are used

### ISSUE THREAD

**Issue by tommyskott** [jitesoft/webpage#4]
Non standard tags were found: `<page/>`

**Comment by tommyskott** [comment]
Self closing tags used on a non-void HTML element. Ignoring the slash and treating as a start tag. This becomes a problem where other tags then seem unclosed.

**Comment by Johannestegner** [comment]
`<page/>` is a vue component, so it is not actually rendered on the page.

**Comment by tommyskott** [comment]
The W3 validator didn't like it. :)
